export const theme = {
  bg: "#FFFFFF",
  bgSecondary: "#F2F2F7",
  bgTertiary: "#E5E5EA",
  ink: "#000000",
  inkMuted: "#3C3C43",
  inkFaint: "#6C6C70",
  border: "rgba(60,60,67,0.18)",
  borderStrong: "rgba(60,60,67,0.36)",
  purple: "#007AFF",
  purpleLight: "#E8F1FF",
  purpleMid: "#409CFF",
  purpleHover: "#0062CC",
  purpleText: "#0051A8",
  green: "#34C759",
  greenLight: "#E8F8ED",
  mono: "'Courier New', monospace",
  serif: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Helvetica Neue', sans-serif",
  sans: "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Helvetica Neue', sans-serif",
  zonaVerde: { color: "#34C759", bg: "#E8F8ED", label: "Zona verde" },
  zonaAmbar: { color: "#FF9500", bg: "#FFF3E0", label: "Zona ámbar" },
  zonaRoja: { color: "#FF3B30", bg: "#FFE8E7", label: "Zona roja" },
  dims: {
    presencia:        "#34C759",
    claridad:         "#FF9500",
    regulacion:       "#AF52DE",
    valores:          "#007AFF",
    autoconocimiento: "#5AC8FA",
    agencia:          "#FF2D55",
  },
};
